import { QuestionDefinition } from "@/lib/diagnostics/types";

const riskOptions = [
  { value: 0 as const, label: "Not true", description: "This is not a meaningful issue in the workflow." },
  { value: 1 as const, label: "Occasional", description: "This shows up sometimes, but usually remains manageable." },
  { value: 2 as const, label: "Frequent", description: "This is a recurring blocker and requires manual workarounds." },
  { value: 3 as const, label: "Systemic", description: "This is structural and routinely undermines trust or speed." },
];

const maturityOptions = [
  { value: 0 as const, label: "Rarely true", description: "There is little clear evidence of this in the workflow." },
  { value: 1 as const, label: "Sometimes true", description: "You can see the pattern, but it breaks down often." },
  { value: 2 as const, label: "Usually true", description: "The pattern holds most of the time, with some visible gaps." },
  { value: 3 as const, label: "Reliably true", description: "The pattern is visible, repeatable, and does not depend on rescue work." },
];

export const questionBank: QuestionDefinition[] = [
  {
    id: "record_disagreement",
    shortLabel: "Record disagreement",
    prompt: "When different teams pull numbers from this workflow, how often do they end up with mismatched records or totals?",
    helpText: "High scores mean people still need reconciliation work before they can trust the output.",
    direction: "risk",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      record_reliability: 1,
      reuse_operating_model: 0.5,
      access_control: 0.2,
    },
    signalWeights: {
      analytical_alignment: 0.3,
      reuse_governance: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "decision_misalignment",
    shortLabel: "Decision misalignment",
    prompt: "How often is this workflow asked to answer a question it was never set up to answer cleanly?",
    helpText: "This checks whether the collected fields still match the real decision people are trying to make.",
    direction: "risk",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      decision_fit: 1,
      quality_discipline: 0.4,
      reuse_operating_model: 0.2,
    },
    signalWeights: {
      analytical_alignment: 0.8,
      quality_loop: 0.3,
    },
    options: riskOptions,
  },
  {
    id: "subjective_capture",
    shortLabel: "Subjective capture",
    prompt: "How much of the important signal still lives in write-ups, judgement calls, or story-based interpretation rather than structured fields?",
    helpText: "High scores mean people must interpret meaning by hand before they can compare or reuse the data.",
    direction: "risk",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      structure_interpretability: 0.8,
      record_reliability: 0.4,
      decision_fit: 0.4,
    },
    signalWeights: {
      structured_data_readiness: 0.7,
      ai_operational_fit: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "access_delay",
    shortLabel: "Access delay",
    prompt: "How often does useful data exist but stay stuck behind approvals, permissions, or slow retrieval?",
    helpText: "This checks whether the workflow is practically reachable when needed, not just theoretically available.",
    direction: "risk",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      access_control: 1,
      reuse_operating_model: 0.3,
    },
    signalWeights: {
      access_reliability: 1,
      reuse_governance: 0.2,
    },
    options: riskOptions,
  },
  {
    id: "input_variability",
    shortLabel: "Input variability",
    prompt: "How often do people improvise at entry time, skip conventions, or type values in inconsistent ways?",
    helpText: "High scores mean the mess is being created during capture, not discovered later.",
    direction: "risk",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      record_reliability: 0.6,
      structure_interpretability: 0.4,
      quality_discipline: 0.7,
    },
    signalWeights: {
      quality_loop: 0.7,
      structured_data_readiness: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "structure_translation",
    shortLabel: "Structure translation",
    prompt: "How often does the team need to reshape messy inputs before even basic analysis can start?",
    helpText: "This captures the recurring cleanup cost of unstructured or mismatched inputs.",
    direction: "risk",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      structure_interpretability: 1,
      decision_fit: 0.2,
      record_reliability: 0.2,
    },
    signalWeights: {
      structured_data_readiness: 0.8,
      ai_operational_fit: 0.5,
    },
    options: riskOptions,
  },
  {
    id: "brittle_reuse",
    shortLabel: "Brittle reuse",
    prompt: "How much does reuse still depend on fragile joins, informal mappings, or person-to-person handoffs?",
    helpText: "High scores mean the workflow breaks easily when it moves across systems or owners.",
    direction: "risk",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      reuse_operating_model: 1,
      record_reliability: 0.4,
      access_control: 0.3,
      structure_interpretability: 0.2,
    },
    signalWeights: {
      reuse_governance: 0.9,
      access_reliability: 0.3,
    },
    options: riskOptions,
  },
  {
    id: "manual_rescue",
    shortLabel: "Manual rescue",
    prompt: "How often does the workflow need spreadsheet patching, one-off fixes, or someone who just knows how it works?",
    helpText: "This shows how much continuity still depends on rescue work instead of a stable process.",
    direction: "risk",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      quality_discipline: 0.5,
      reuse_operating_model: 0.7,
      record_reliability: 0.3,
    },
    signalWeights: {
      capture_foundation: 0.5,
      reuse_governance: 0.3,
    },
    options: riskOptions,
  },
  {
    id: "capture_foundation",
    shortLabel: "Stable capture",
    prompt: "How much of this workflow runs through stable digital steps rather than improvised manual gathering?",
    helpText: "This checks whether the workflow has a dependable capture base.",
    direction: "maturity",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      access_control: 0.2,
      quality_discipline: 0.2,
      reuse_operating_model: 0.2,
    },
    signalWeights: {
      capture_foundation: 1,
    },
    options: maturityOptions,
  },
  {
    id: "analytical_alignment",
    shortLabel: "Decision fit",
    prompt: "How deliberately are fields, definitions, and update timing matched to the job this workflow needs to do?",
    helpText: "This is the positive signal that the workflow was set up for the current use, not borrowed for it.",
    direction: "maturity",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      decision_fit: 0.7,
      reuse_operating_model: 0.2,
    },
    signalWeights: {
      analytical_alignment: 1,
    },
    options: maturityOptions,
  },
  {
    id: "quality_management",
    shortLabel: "Quality routine",
    prompt: "How consistent is the routine for checking quality, spotting issues, and correcting them?",
    helpText: "This looks for an active quality habit, not one-off inspection after problems spread.",
    direction: "maturity",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      quality_discipline: 0.8,
      record_reliability: 0.2,
    },
    signalWeights: {
      quality_loop: 1,
    },
    options: maturityOptions,
  },
  {
    id: "reuse_governance",
    shortLabel: "Clear ownership",
    prompt: "Is it clear who creates the data, maintains it, uses it, and decides when it should change?",
    helpText: "This checks whether reuse runs on explicit responsibility instead of personal memory.",
    direction: "maturity",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      reuse_operating_model: 0.8,
      access_control: 0.2,
    },
    signalWeights: {
      reuse_governance: 1,
      access_reliability: 0.2,
    },
    options: maturityOptions,
  },
  {
    id: "ai_usability",
    shortLabel: "AI reuse readiness",
    prompt: "If you pointed a narrow AI task at this workflow tomorrow, how much cleanup would be needed first?",
    helpText: "Stay conservative. Low scores are normal and often the honest answer.",
    direction: "maturity",
    productTypes: ["dq", "drl"],
    scopeTypes: ["use_case", "organization"],
    dimensionWeights: {
      structure_interpretability: 0.5,
      record_reliability: 0.3,
      decision_fit: 0.4,
    },
    signalWeights: {
      structured_data_readiness: 0.7,
      ai_operational_fit: 1,
    },
    options: maturityOptions,
  },
];
